name: Deploy Vite to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Show npm version
        run: npm -v

      - name: Clean npm cache (workaround rollup optional deps)
        run: npm cache clean --force

      - name: Install dependencies (prefer lockfile)
        run: |
          if [ -f package-lock.json ]; then
            npm ci || (rm -rf node_modules package-lock.json && npm install)
          else
            npm install
          fi

      - name: Build
        env:
          GITHUB_PAGES: "true"
          REPO_NAME: ${{ github.event.repository.name }}
          # force Rollup to skip native binary (uses JS fallback)
          ROLLUP_SKIP_NODEJS_NATIVE: "1"
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
